db:
  ignore_unknown_table_columns: false
log:
  level: panic
  leak_sensitive_values: false
  redaction_text: ""
  format: json
serve:
  public:
    host: 0.0.0.0
    port: 4444
    tls:
      enabled: false
  admin:
    host: 0.0.0.0
    port: 4445
    tls:
      enabled: false
  cookies:
    same_site_mode: Lax

dsn: postgres://hydra:hydra_pass123@postgres:5432/hydra?sslmode=disable

urls:
  self:
    issuer: http://localhost:4444
  login: http://localhost:3000/login
  consent: http://localhost:3000/consent
  logout: http://localhost:3000/logout
  error: http://localhost:3000/error
  post_logout_redirect: http://localhost:3000/logout-successful

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
oauth2:
  mirror_top_level_claims: false