version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: hydra-postgres
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra_pass123
      POSTGRES_DB: hydra
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  hydra-migrate:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:hydra_pass123@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes
    restart: "no"

  hydra:
    image: oryd/hydra:v2.2
    container_name: hydra
    depends_on:
      - hydra-migrate
    environment:
      - DSN=postgres://hydra:hydra_pass123@postgres:5432/hydra?sslmode=disable
    volumes:
      - ./hydra/config:/etc/hydra
    command: serve all --dev -c /etc/hydra/hydra.yml
    ports:
      - "4444:4444"
      - "4445:4445"
    restart: unless-stopped

  hydra-init:
    image: alpine:latest
    container_name: hydra-init
    depends_on:
      - hydra
    user: root
    volumes:
      - ./init:/init
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache bash curl gettext && /init/init-hydra.sh"]
    restart: "no"
    environment:
#      CLIENT_ID: ${CLIENT_ID_COMPOSE}
      REDIRECT_URI: ${REDIRECT_URI_COMPOSE}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN_COMPOSE}
      HYDRA_ADMIN_URL: ${HYDRA_ADMIN_URL_COMPOSE}

#  hydra-init:
#    image: curlimages/curl:latest
#    container_name: hydra-init
#    depends_on:
#      - hydra
#    volumes:
#      - ./init:/init
#    entrypoint: ["/bin/sh", "/init/init-hydra.sh"]
#    restart: "no"
#    user: root
#    environment:
#      CLIENT_ID: hydra-flow-client-generated
#      REDIRECT_URI: http://localhost:3000/redirect-uri
#      ALLOWED_ORIGIN: http://localhost:3000
#      HYDRA_ADMIN_URL: http://hydra:4445

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydra-flow-client
    volumes:
      - ./app:/app/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload --log-level debug
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - hydra
    restart: unless-stopped

volumes:
  pgdata:
