apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
data:
  hydra.yml: |
    serve:
      public:
        host: 0.0.0.0
        port: 4444
        tls:
          enabled: false
      admin:
        host: 0.0.0.0
        port: 4445
        tls:
          enabled: false
    dsn: postgres://hydra:hydra_pass123@postgres:5432/hydra?sslmode=disable
    urls:
      self:
        issuer: http://hydra:4444
      login: http://hydra-flow-client:3000/login
      consent: http://hydra-flow-client:3000/consent
      logout: http://hydra-flow-client:3000/logout
    secrets:
      system:
        - youReallyNeedToChangeThis
    oidc:
      subject_identifiers:
        supported_types:
          - pairwise
          - public
        pairwise:
          salt: youReallyNeedToChangeThis
