apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
        - name: hydra
          image: oryd/hydra:v2.2
          ports:
            - containerPort: 4444
            - containerPort: 4445
          volumeMounts:
            - name: hydra-config
              mountPath: /etc/hydra
          command: [ "serve", "all", "--dev", "-c", "/etc/hydra/hydra.yml" ]
          env:
            - name: DSN
              value: postgres://hydra:hydra_pass123@postgres:5432/hydra?sslmode=disable
      volumes:
        - name: hydra-config
          configMap:
            name: hydra-config
