apiVersion: v1
kind: ConfigMap
metadata:
  name: init-client-config
data:
  client.json: |
    {
      "client_id": "hydra-flow-client",
      "client_secret": "super-secret",
      "redirect_uris": ["http://hydra-flow-client:3000/redirect-uri"],
      "grant_types": ["authorization_code"],
      "response_types": ["code", "id_token"],
      "scope": "openid offline",
      "token_endpoint_auth_method": "client_secret_post",
      "post_logout_redirect_uris": ["http://hydra-flow-client:3000"]
    }
